plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.4'
    id 'io.spring.dependency-management' version '1.1.6'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.ai:spring-ai-bom:1.0.0'
        mavenBom 'com.alibaba.cloud.ai:spring-ai-alibaba-bom:1.0.0.2'
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'
    implementation 'org.springframework.ai:spring-ai-vector-store'
    implementation 'org.springframework.ai:spring-ai-rag'
    implementation 'com.alibaba.cloud.ai:spring-ai-alibaba-graph-core'
    implementation 'com.google.code.gson:gson'
}
